version: '3.8'

services:
    app:
        build:
            context: .
        container_name: app
        working_dir: /var/www
        volumes:
            - app-data:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /var/www
        volumes:
            - app-data:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-data:
        driver: local
    dbdata:
        driver: local
